name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Show Node version
        run: node -v && npm -v
          
      - name: Install root dependencies
        run: npm install
        
      - name: Add Firebase Tokens
        run: |
          echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT=ai-content-creator-f7d53" >> $GITHUB_ENV
          echo "Building for project $FIREBASE_PROJECT"
          
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
          
      - name: Check package versions
        run: |
          cd frontend
          echo "Checking package versions..."
          npm list ajv ajv-keywords || true
          
      - name: Build frontend
        run: |
          cd frontend
          DISABLE_ESLINT_PLUGIN=true GENERATE_SOURCEMAP=false CI=false npm run build
          
      - name: Verify build output
        run: |
          ls -la frontend/build || echo "Build directory not found!"
          
      - name: Install functions dependencies
        run: |
          cd functions
          npm install
        continue-on-error: true
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_CONTENT_CREATOR_F7D53 }}'
          channelId: live
          projectId: ai-content-creator-f7d53
